from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet

words = "cats running ran cactus cactuses cacti community communities".split()
sentences = [
":( RT @Dentdocdekky: Depressing #MUFC",
"Double meaning \"@izzatluqmaan: In Moyes we trust ! Keep up the good work :D\"",
"Loving the match between Man United and Newcastle!!!! =)) #UnitedRocks =)) lmfao!! *Doing the Sturridge*  Newcastle 1-0 Man United pffft!",
"@gigi_salmon 3:1 for #CFC, Hazard, Mata and Torres :]",
"Yes Newcastle! :)",
"I just love Manchester United!:)",
"MU :)) Losing to Newcastle :)) #GGNewcastle",
"Chelsea Grin ou Suicide Silence :/",
"Good luck Wilfried Zaha :) This is your moment! #MUFC",
"@FootballFunnys: Moyes bringing his son in law on.. dunno why this is so funny(((:",
"Ryan giggs is better\"@am_sweezy: Can they just sack moyes plsssz.... Dont worry Rooney will coach us :( :(\"",
"Its manutd's fault :(\"@_Lightningfox: Lmao!!! Pipe!!!! \"@Gbemiga_AD: I don't like football anymore :( , I love skipping now.\"\"",
"@Khairykj Now everyone can win @ Old Trafford? :)",
":)) RT @FootballFunnys: Live pictures of David Moyes http://t.co/I5VVkENfDE",
"Nani..please die soon :) you are shit.. pass on that talent to someone who is actually capable LOL",
"Thank you Newcastle now just keep it like this :)",
"@AlexanderWilko Easy win for Man United at Old Trafford :D",
"@skumar176 mou mou mourinho..arrogant but sweet? Haha, he is the special one :)",
"@biffa69 Dropped Cabaye? Ouch mate :D",
"Game Chelsea Or futsall tonight ? :/",
"God, where will Manchester United end this season. :-(",
"Azzin! Awon aye! @Smalldeefinest: :o Now now? Wow \"@TrendsLagos 'cabaye' is now trending in #Lagos http://t.co/gUk7aKGgiw\"",
"@TheBlue_Print I take back everything I said about Cabaye :D",
"Man United 1-0 Newcastle. Poor from Evra! :(( #MUFC #GGMU",
"@27_DrW: nani valencia young Ferdinand cleverly anderson vidic evra all need to be shown the door! start rebuilding #MUFC vidic? ;)",
"@gigi_salmon Chelsea 3-1 Stoke JT Torres Mata on scoresheet :) #Chelsea",
"@smallingindo BLUNDER EVRA Oh MY GOD.... :( :'(",
"ahahahahah 0-1 motherfucker ;) RT \"@fznshmt: I STILL SUPPORT MANCHESTER UNITED NO MATTER WHAT HAPPENS NEXT SO FUCK OFF",
"Happy birthday John Terry :)",
"Anderson and Zaha come on to try save the match :) Ahhh our squad depth. #MUFC",
"C'mon Newcastle!! :)) RT @VIVAbola: Manchester United [0-1] Newcastle United : Menit 61\" Y. Cabaye (GOL) http://t.co/54Ko8MvBC8",
"Anyway, 20 more minutes. Hold on Newcastle :)",
"LOOOOOOOOOOL what is an Anderson? :/",
"Get the flags out, here comes fat Ando 2 tbe rescue...:/ #MUFC",
"Newcastle goal :( bitch pleaseee",
"Finally Moyes is letting his future son-in-law play :) yaay Zaha :D",
"FUCK YOU @ManUtd :)",
"yaampuun :( \"@UtdIndnesiaBALI: 60' : Man United 0 - 1 Newcastle Utd (Cabaye 60') #MUNNEW\"",
"LOL\"@omojuwa: Awww. De Gea almost caught the ball. It wouldn't have gone in had the ball delayed a bit :( #MTNfootball\"",
"@EL_DEINO: Because he's a player? \"@dolapo_obat: Why is Moyes playing Nani?\" Haha! My bad, I din't know that. :)",
"Oh ref please blow that whistle now ;) #NUFC",
"@TatianaMUFC maybe fellaini was trying to think of a tweet earlier on the bench. ;)",
"Glory-Glory Manchester United >=)",
"Still cant believe Newcastle are winning=))",
"Manchester United... What is happening... :/",
"Well done Moyes, you make me want to hire Agent 47 :-)",
"SUBSTITUTION : Moyes Out - Ferguson In . :D hahaha just kidding #InMoyesWeTrust",
"@FootyHumour Our article on Moyes :) http://t.co/vMN8O61Pn8",
"Moyes is now the most popular manager in the Premiership except in Manchester. ;) #MoyesIn",
"Okay seems like I am not the only one who thinks Vidic looks like Woody Harrelson :D http://t.co/QYaJI3eDFM",
"@Toco464 don't let Tozzles hear you saying that!! he says derby up stoke down... Struggling to disagree with him :/ #chelseaathometoday :|",
"@Zackone_04 Newcastle goal :(",
"Imagine the names we were linked with. Jose, klopp and pep. We got moyes :/ like going to a brothel and getting cuddles ffs!",
"@angeebfly Moyes... More, Yes... :-)",
"Lol , its manutd that caused it :(\"@yomihypes: \"@Gbemiga_AD: I don't like football anymore :( , I love skipping now.\" faggit\"",
"I'm gonna take my words \"don't sack moyes\". The club should think about keeping moyes more longer. Really. But.... We are not chelsea :((",
"Newcastle :( show mercy please",
"@TobiiasGaming MU is loosing against newcastle :)",
":( \"@evilkagawa: I going sleep. Wake Kagawa when United score. I probably still be sleep at Christmas!  No play-a-making sons of bitches!\"",
"@JoeKelleher1 @donovanemile @cridheone @WitchMysticia Stay positive everyone, we can really do this! :) #UseTheForce #OneLove #MUFC",
"Man United have one more sub left, they should bring on Sir Alex for David Moyes! ;)",
"Jose Mourinho: \"Man United still in race \"   | 6 Teams can win the Premier League :))",
"Man u is really crazy\"@dadspet5: Moyes... :D destroying Man U... What a feeling ",
"If Lampard feels hard done, can't blame him. Brilliant vs. Sunderland and dropped. Yet Ramires gets to play every game:(",
"Lwkmd! \"@ades_dami E go shock you\"Smalldeefinest: Am porting to Mufc!!!! :D\"\"",
"Iya bro iya :( \"@vdsar1970: Oh oh this is not looking to good today at Old Trafford! Need to raise a lot more then just their game! @ManUtd\"",
"Need three points today lads #MCFC @MCFC c'mon city!!:)",
"cc @saididu :D RT @premierleague: SUB Wilfried Zaha comes on to make his #BPL debut, replacing Nani. Man Utd 0-1 Newcastle (68 mins) #MUNNEW",
"Get in there Newcastle united!!! Fvck everyone at Manchester United :)",
"@SamJohno_  PARDEW IS OUR KING ;)",
"Manchester United :(",
"In Moyes I'm fully trust :D",
"I really am struggling with this :( what are you doing lads!! Sort it out #MUFC",
"manchester united... i'm speechless :((",
"IOOOOOOOOMMMGGGGGGG LOOOOL :((((((((2-0 Newcastle",
"@my_supersoccer kan Moyes The Chosen One :) http://t.co/DS03YiEtoF",
"Lmfao @ProvyHernandez: Jose Mourinho: \"Man United still in race \"   | 6 Teams can win the Premier League :))",
"Goodjob MU goodjob Moyes :D",
"Zahaaa went ahaaa on Moyes's Daughtaaaa ..... :P",
"HOLY FUCK. 1-0 DOWN??? Is it a deserved lead for Newcastle or can't we score again? :(",
"Cabayeeeeee :) :D xXXx #nufc",
"Na so\"@AVARIBERRY: Sooooooo does ur team need 3 points? Come to Man Utd... Old Trafford... we are sharing it. :-)\"",
"Manchester United why don't you win anymore ??  :( :(",
"K \"@Smalldeefinest: Am porting to Mufc!!!! :D\"",
"@OfficialMgh We are ramming you right up the ass dude, chelsea would possibly be 1 point behind you, GL :)",
"Moyes sacked and relegation haha ;)",
"@KSIOlajidebt: Man, i better start betting against Manchester United at this rate. I could be making BANK XD @ManUtd",
"Come back:)RT @vdsar1970: Oh oh this is not looking to good today at Old Trafford! Need to raise a lot more then just their game! @ManUtd",
"I doubt his stay in chelsea remains longer :( @niloykc",
"WBA won at Old Trafford after 35years, Everton after 20 years...now Newcastle is winning after 41 years-Moyes is The Recordbreaker:D #MANNEW",
"Wicked \"@omojuwa: Awww. De Gea almost caught the ball. It wouldn't have gone in had the ball delayed a bit :( #MTNfootball\"",
"Moyes I can't do this anymore:( Man U I can't do this shit anymore:'( WE NEED SAF....SAF come back http://t.co/KjcyxKWRZ1",
"Optimis 3 poin malam ini :D \"@ChelseaMalang: C'mon Chelsea! #CFC #KTBFFH http://t.co/oY70a5snYP\"",
"@Tlams1 vidic, evra, giggs, ferdinand, van p, carrick.. the engine room is tired :)",
"Mata starts for Chelsea again. Mou know what he's doing :)",
"Oh RvP how we have missed you :)",
"I've had to set off to work :( keep me updated! #nufc",
"Gaaaaaaa! Ref is on drugs :( #MUFC",
"@dolapo_obat: @EL_DEINO: Because he's a player? @dolapo_obat: Why is Moyes playing Nani?\" Haha! My bad, I din't know that. :)\" issorait",
"Anyone got David Moyes address. I want to send him a Christmas card :)"
]

lemat = WordNetLemmatizer()
for sentence in sentences:
    words = sentence.split()
    print sentence
    for w in words:
        print w, "-", lemat.lemmatize(w)
    print ""
